[package]
name = "mahf"
version = "0.1.0"
authors = ["Leopold Luley <git@leopoldluley.de>"]
edition = "2018"

[workspace]
members = ["param-study"]

[dependencies]
anyhow = "1.0.40"
embed-doc-image = "0.1.4"
erased-serde = "0.3.13"
float_eq = "0.6.0"
itoa = "0.4.7"
num_cpus = "1.13.0"
pest = "2.1.3"
pest_consume = "1.0.6"
pest_derive = "2.1.0"
rand = "0.8.3"
rand_distr = "0.4.0"
ron = "0.6.4"
rprompt = "1.0.5"
ryu = "1.0.5"
serde = { version = "1.0.125", features = ["derive"] }

[dev-dependencies]
proptest = "1.0.0"

[build-dependencies]
cc = "1.0.67"
