[package]
name = "mahf"
version = "0.1.0"
authors = ["Leopold Luley <git@leopoldluley.de>"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
erased-serde = "0.3.13"
num_cpus = "1.13.0"
rand = "0.8.3"
rand_distr = "0.4.0"
ron = "0.6.4"
rprompt = "1.0.5"
serde = { version = "1.0.125", features = ["derive"] }
