[package]
authors = ["Leopold Luley <git@leopoldluley.de>"]
edition = "2021"
name = "mahf"
version = "0.1.0"

[workspace]
members = ["param-study"]

[dependencies]
anyhow = "1.0.51"
embed-doc-image = "0.1.4"
erased-serde = "0.3.16"
float_eq = "0.7.0"
itoa = "1.0.1"
num_cpus = "1.13.0"
pest = "2.1.3"
pest_consume = "1.1.1"
pest_derive = "2.1.0"
rand = "0.8.4"
rand_distr = "0.4.2"
ron = "0.7.0"
rprompt = "1.0.5"
ryu = "1.0.9"
serde = { version = "1.0.131", features = ["derive"] }
coco-rs = "0.3"

[dev-dependencies]
proptest = "1.0.0"

[build-dependencies]
cc = "1.0.72"
