[package]
authors = ["Leopold Luley <git@leopoldluley.de>"]
edition = "2021"
name = "mahf"
version = "0.1.0"

[dependencies]
anyhow = "1.0.51"
ciborium = "0.2.0"
coco-rs = "0.4"
derive_deref = "1.1.1"
embed-doc-image = "0.1.4"
erased-serde = "0.3.16"
float_eq = "0.7.0"
num_cpus = "1.13.0"
pest = "2.1.3"
pest_consume = "1.1.1"
pest_derive = "2.1.0"
rand = "0.8.4"
rand_distr = "0.4.2"
ron = "0.7.0"
rprompt = "1.0.5"
serde = {version = "1.0.131", features = ["derive"]}
trait-set = "0.3.0"

[dev-dependencies]
proptest = "1.0.0"

[build-dependencies]
cc = "1.0.72"
