imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# We don't want this enabled permanently or in the CI because some doc test formatting is pretty horrible.
# For imports, it's very handy, though.
# format_code_in_doc_comments = true