on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  RUST_VERSION: 1.66.1
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ env.RUST_VERSION }}
          override: true
          components: rustfmt, clippy
    - name: Format
      run: cargo fmt --all -- --check --verbose
    - name: Clippy
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings
    - name: Build
      run: cargo build --verbose
    - name: Tests
      run: cargo test --workspace --all-targets --all-features --verbose